apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audit-service.yaml
  - chat-service.yaml
  - common-service.yaml
  - config-server.yaml
  - configmap-common.yaml
  - delivery-service.yaml
  - eureka-server.yaml
  - frontend.yaml
  - gateway-service.yaml
  - ingress.yaml
  - inventory-service.yaml
  - notification-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - product-comment-service.yaml
  - product-media-service.yaml
  - product-review-service.yaml
  - product-service.yaml
  - reporting-service.yaml
  - shipping-service.yaml
  - user-service.yaml
