server:
  port: 8092
spring:
  application:
    name: product-media-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  mongodb:
    uri: mongodb://${MONGO_HOST:localhost:27017}/${MONGO_DB:media}${MONGO_REPLICA_SET_PARAM:}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

media:
  upload-dir: ${MEDIA_UPLOAD_DIR:media-uploads}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false

keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/demo}
  jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/demo/protocol/openid-connect/certs}

management:
  endpoint:
    health:
      probes:
        enabled: true

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:demo-wilbert}
