apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - elasticsearch.yaml
  - kafka.yaml
  - keycloak.yaml
  - mailpit.yaml
  - mongo-configsvr.yaml
  - mongo-shard0.yaml
  - mongo-shard1.yaml
  - mongo-mongos.yaml
  - mongo-cluster-init-job.yaml
  - mongo-cluster-self-heal-cronjob.yaml
  - mysql.yaml
  - promtail-daemonset.yaml
  - redis.yaml
  - vault.yaml
