apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: demo
  labels: { app: audit-service, monitored: "true" }
spec:
  replicas: 1
  selector: { matchLabels: { app: audit-service } }
  template:
    metadata: { labels: { app: audit-service, monitored: "true" } }
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: audit-service
          image: ghcr.io/wilbertjoosen/demo-audit-service:1.0.0
          imagePullPolicy: Always
          ports: [{ containerPort: 8090 }]
          envFrom:
            - configMapRef: { name: demo-common-config }
          env:
            - { name: EUREKA_INSTANCE_HOSTNAME, value: audit-service }
          resources:
            requests: { cpu: "250m", memory: "448Mi" }
            limits: { cpu: "1", memory: "768Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8090 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8090 }
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: demo
  labels: { monitored: "true" }
spec:
  selector: { app: audit-service }
  ports: [{ name: http, port: 8090, targetPort: 8090 }]
