apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: demo
  labels: { app: gateway-service, monitored: "true" }
spec:
  replicas: 1
  selector: { matchLabels: { app: gateway-service } }
  template:
    metadata: { labels: { app: gateway-service, monitored: "true" } }
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: gateway-service
          image: ghcr.io/wilbertjoosen/demo-gateway-service:bd8e5e27d95eb1b6499c6f7971d0a0c289eba3f1
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          envFrom:
            - configMapRef: { name: demo-common-config }
          env:
            - { name: EUREKA_INSTANCE_HOSTNAME, value: gateway-service }
          resources:
            requests: { cpu: "150m", memory: "256Mi" }
            limits: { cpu: "500m", memory: "384Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: demo
  labels: { monitored: "true" }
spec:
  selector: { app: gateway-service }
  ports: [{ name: http, port: 8080, targetPort: 8080 }]
