apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: demo-qa
  labels: { app: payment-service, monitored: "true" }
spec:
  replicas: 1
  selector: { matchLabels: { app: payment-service } }
  template:
    metadata: { labels: { app: payment-service, monitored: "true" } }
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: payment-service
          image: ghcr.io/wilbertjoosen/demo-payment-service:1.0.0
          imagePullPolicy: Always
          ports: [{ containerPort: 8086 }]
          envFrom:
            - configMapRef: { name: demo-common-config }
          env:
            - { name: EUREKA_INSTANCE_HOSTNAME, value: payment-service }
            - { name: MONGO_DB, value: payments_qa }
          resources:
            requests: { cpu: "200m", memory: "384Mi" }
            limits: { cpu: "750m", memory: "640Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8086 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8086 }
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: demo-qa
  labels: { monitored: "true" }
spec:
  selector: { app: payment-service }
  ports: [{ name: http, port: 8086, targetPort: 8086 }]
