apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: demo
  labels: { app: shipping-service, monitored: "true" }
spec:
  replicas: 1
  selector: { matchLabels: { app: shipping-service } }
  template:
    metadata: { labels: { app: shipping-service, monitored: "true" } }
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: shipping-service
          image: ghcr.io/wilbertjoosen/demo-shipping-service:1.0.1-7e68f28
          imagePullPolicy: Always
          ports: [{ containerPort: 8088 }]
          envFrom:
            - configMapRef: { name: demo-common-config }
          env:
            - { name: EUREKA_INSTANCE_HOSTNAME, value: shipping-service }
            - { name: MONGO_DB, value: shipments }
          resources:
            requests: { cpu: "200m", memory: "384Mi" }
            limits: { cpu: "750m", memory: "640Mi" }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8088 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8088 }
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: demo
  labels: { monitored: "true" }
spec:
  selector: { app: shipping-service }
  ports: [{ name: http, port: 8088, targetPort: 8088 }]
