apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - k6.yaml
  - kibana.yaml
  - kube-state-metrics.yaml
  - loki.yaml
  - node-exporter.yaml
  - prometheus.yaml
  - pyroscope.yaml
  - tempo.yaml
