spring:
  mongodb:
    uri: mongodb://${MONGO_HOST:localhost:27017}/${MONGO_DB:orders}${MONGO_REPLICA_SET_PARAM:}
  security:
    oauth2:
      client:
        provider:
          inventory-service:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak.localhost:8081/realms/demo/protocol/openid-connect/token}

keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI:http://keycloak.localhost:8081/realms/demo}
  jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak.localhost:8081/realms/demo/protocol/openid-connect/certs}
